package com.zhonggu.monitor.model;

import java.util.Date;

public class EventTrace {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event_trace.id
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event_trace.module_name
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event_trace.event_name
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    private String eventName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event_trace.trace_key
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    private String traceKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event_trace.event_stage
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    private Integer eventStage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event_trace.thread_id
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    private String threadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event_trace.trace_data
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    private String traceData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_event_trace.trace_time
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    private Date traceTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event_trace.id
     *
     * @return the value of t_event_trace.id
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_event_trace.id
     *
     * @param id the value for t_event_trace.id
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event_trace.module_name
     *
     * @return the value of t_event_trace.module_name
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_event_trace.module_name
     *
     * @param moduleName the value for t_event_trace.module_name
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event_trace.event_name
     *
     * @return the value of t_event_trace.event_name
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_event_trace.event_name
     *
     * @param eventName the value for t_event_trace.event_name
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event_trace.trace_key
     *
     * @return the value of t_event_trace.trace_key
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public String getTraceKey() {
        return traceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_event_trace.trace_key
     *
     * @param traceKey the value for t_event_trace.trace_key
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public void setTraceKey(String traceKey) {
        this.traceKey = traceKey == null ? null : traceKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event_trace.event_stage
     *
     * @return the value of t_event_trace.event_stage
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public Integer getEventStage() {
        return eventStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_event_trace.event_stage
     *
     * @param eventStage the value for t_event_trace.event_stage
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public void setEventStage(Integer eventStage) {
        this.eventStage = eventStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event_trace.thread_id
     *
     * @return the value of t_event_trace.thread_id
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public String getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_event_trace.thread_id
     *
     * @param threadId the value for t_event_trace.thread_id
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public void setThreadId(String threadId) {
        this.threadId = threadId == null ? null : threadId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event_trace.trace_data
     *
     * @return the value of t_event_trace.trace_data
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public String getTraceData() {
        return traceData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_event_trace.trace_data
     *
     * @param traceData the value for t_event_trace.trace_data
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public void setTraceData(String traceData) {
        this.traceData = traceData == null ? null : traceData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_event_trace.trace_time
     *
     * @return the value of t_event_trace.trace_time
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public Date getTraceTime() {
        return traceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_event_trace.trace_time
     *
     * @param traceTime the value for t_event_trace.trace_time
     *
     * @mbggenerated Mon Jun 11 17:28:36 CST 2018
     */
    public void setTraceTime(Date traceTime) {
        this.traceTime = traceTime;
    }
}