package com.zhonggu.monitor.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EventTraceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public EventTraceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andModuleNameIsNull() {
            addCriterion("module_name is null");
            return (Criteria) this;
        }

        public Criteria andModuleNameIsNotNull() {
            addCriterion("module_name is not null");
            return (Criteria) this;
        }

        public Criteria andModuleNameEqualTo(String value) {
            addCriterion("module_name =", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotEqualTo(String value) {
            addCriterion("module_name <>", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameGreaterThan(String value) {
            addCriterion("module_name >", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameGreaterThanOrEqualTo(String value) {
            addCriterion("module_name >=", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameLessThan(String value) {
            addCriterion("module_name <", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameLessThanOrEqualTo(String value) {
            addCriterion("module_name <=", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameLike(String value) {
            addCriterion("module_name like", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotLike(String value) {
            addCriterion("module_name not like", value, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameIn(List<String> values) {
            addCriterion("module_name in", values, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotIn(List<String> values) {
            addCriterion("module_name not in", values, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameBetween(String value1, String value2) {
            addCriterion("module_name between", value1, value2, "moduleName");
            return (Criteria) this;
        }

        public Criteria andModuleNameNotBetween(String value1, String value2) {
            addCriterion("module_name not between", value1, value2, "moduleName");
            return (Criteria) this;
        }

        public Criteria andEventNameIsNull() {
            addCriterion("event_name is null");
            return (Criteria) this;
        }

        public Criteria andEventNameIsNotNull() {
            addCriterion("event_name is not null");
            return (Criteria) this;
        }

        public Criteria andEventNameEqualTo(String value) {
            addCriterion("event_name =", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotEqualTo(String value) {
            addCriterion("event_name <>", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameGreaterThan(String value) {
            addCriterion("event_name >", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameGreaterThanOrEqualTo(String value) {
            addCriterion("event_name >=", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameLessThan(String value) {
            addCriterion("event_name <", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameLessThanOrEqualTo(String value) {
            addCriterion("event_name <=", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameLike(String value) {
            addCriterion("event_name like", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotLike(String value) {
            addCriterion("event_name not like", value, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameIn(List<String> values) {
            addCriterion("event_name in", values, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotIn(List<String> values) {
            addCriterion("event_name not in", values, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameBetween(String value1, String value2) {
            addCriterion("event_name between", value1, value2, "eventName");
            return (Criteria) this;
        }

        public Criteria andEventNameNotBetween(String value1, String value2) {
            addCriterion("event_name not between", value1, value2, "eventName");
            return (Criteria) this;
        }

        public Criteria andTraceKeyIsNull() {
            addCriterion("trace_key is null");
            return (Criteria) this;
        }

        public Criteria andTraceKeyIsNotNull() {
            addCriterion("trace_key is not null");
            return (Criteria) this;
        }

        public Criteria andTraceKeyEqualTo(String value) {
            addCriterion("trace_key =", value, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyNotEqualTo(String value) {
            addCriterion("trace_key <>", value, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyGreaterThan(String value) {
            addCriterion("trace_key >", value, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyGreaterThanOrEqualTo(String value) {
            addCriterion("trace_key >=", value, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyLessThan(String value) {
            addCriterion("trace_key <", value, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyLessThanOrEqualTo(String value) {
            addCriterion("trace_key <=", value, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyLike(String value) {
            addCriterion("trace_key like", value, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyNotLike(String value) {
            addCriterion("trace_key not like", value, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyIn(List<String> values) {
            addCriterion("trace_key in", values, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyNotIn(List<String> values) {
            addCriterion("trace_key not in", values, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyBetween(String value1, String value2) {
            addCriterion("trace_key between", value1, value2, "traceKey");
            return (Criteria) this;
        }

        public Criteria andTraceKeyNotBetween(String value1, String value2) {
            addCriterion("trace_key not between", value1, value2, "traceKey");
            return (Criteria) this;
        }

        public Criteria andThreadIdIsNull() {
            addCriterion("thread_id is null");
            return (Criteria) this;
        }

        public Criteria andThreadIdIsNotNull() {
            addCriterion("thread_id is not null");
            return (Criteria) this;
        }

        public Criteria andThreadIdEqualTo(String value) {
            addCriterion("thread_id =", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdNotEqualTo(String value) {
            addCriterion("thread_id <>", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdGreaterThan(String value) {
            addCriterion("thread_id >", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdGreaterThanOrEqualTo(String value) {
            addCriterion("thread_id >=", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdLessThan(String value) {
            addCriterion("thread_id <", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdLessThanOrEqualTo(String value) {
            addCriterion("thread_id <=", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdLike(String value) {
            addCriterion("thread_id like", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdNotLike(String value) {
            addCriterion("thread_id not like", value, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdIn(List<String> values) {
            addCriterion("thread_id in", values, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdNotIn(List<String> values) {
            addCriterion("thread_id not in", values, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdBetween(String value1, String value2) {
            addCriterion("thread_id between", value1, value2, "threadId");
            return (Criteria) this;
        }

        public Criteria andThreadIdNotBetween(String value1, String value2) {
            addCriterion("thread_id not between", value1, value2, "threadId");
            return (Criteria) this;
        }

        public Criteria andTraceTimeIsNull() {
            addCriterion("trace_time is null");
            return (Criteria) this;
        }

        public Criteria andTraceTimeIsNotNull() {
            addCriterion("trace_time is not null");
            return (Criteria) this;
        }

        public Criteria andTraceTimeEqualTo(Date value) {
            addCriterion("trace_time =", value, "traceTime");
            return (Criteria) this;
        }

        public Criteria andTraceTimeNotEqualTo(Date value) {
            addCriterion("trace_time <>", value, "traceTime");
            return (Criteria) this;
        }

        public Criteria andTraceTimeGreaterThan(Date value) {
            addCriterion("trace_time >", value, "traceTime");
            return (Criteria) this;
        }

        public Criteria andTraceTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("trace_time >=", value, "traceTime");
            return (Criteria) this;
        }

        public Criteria andTraceTimeLessThan(Date value) {
            addCriterion("trace_time <", value, "traceTime");
            return (Criteria) this;
        }

        public Criteria andTraceTimeLessThanOrEqualTo(Date value) {
            addCriterion("trace_time <=", value, "traceTime");
            return (Criteria) this;
        }

        public Criteria andTraceTimeIn(List<Date> values) {
            addCriterion("trace_time in", values, "traceTime");
            return (Criteria) this;
        }

        public Criteria andTraceTimeNotIn(List<Date> values) {
            addCriterion("trace_time not in", values, "traceTime");
            return (Criteria) this;
        }

        public Criteria andTraceTimeBetween(Date value1, Date value2) {
            addCriterion("trace_time between", value1, value2, "traceTime");
            return (Criteria) this;
        }

        public Criteria andTraceTimeNotBetween(Date value1, Date value2) {
            addCriterion("trace_time not between", value1, value2, "traceTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_event_trace
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 08 18:10:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_event_trace
     *
     * @mbggenerated Fri Jun 08 18:10:01 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}