package com.zhonggu.monitor.model;

public class TraceCfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trace_cfg.id
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trace_cfg.model_name
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trace_cfg.trace_key
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    private String traceKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trace_cfg.is_on
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    private Boolean isOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trace_cfg.id
     *
     * @return the value of t_trace_cfg.id
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trace_cfg.id
     *
     * @param id the value for t_trace_cfg.id
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trace_cfg.model_name
     *
     * @return the value of t_trace_cfg.model_name
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trace_cfg.model_name
     *
     * @param modelName the value for t_trace_cfg.model_name
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trace_cfg.trace_key
     *
     * @return the value of t_trace_cfg.trace_key
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    public String getTraceKey() {
        return traceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trace_cfg.trace_key
     *
     * @param traceKey the value for t_trace_cfg.trace_key
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    public void setTraceKey(String traceKey) {
        this.traceKey = traceKey == null ? null : traceKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trace_cfg.is_on
     *
     * @return the value of t_trace_cfg.is_on
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    public Boolean getIsOn() {
        return isOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trace_cfg.is_on
     *
     * @param isOn the value for t_trace_cfg.is_on
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    public void setIsOn(Boolean isOn) {
        this.isOn = isOn;
    }
}