package com.zhonggu.monitor.dao;

import com.zhonggu.monitor.model.TraceCfg;
import com.zhonggu.monitor.model.TraceCfgExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TraceCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    int countByExample(TraceCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    int deleteByExample(TraceCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    int insert(TraceCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    int insertSelective(TraceCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    List<TraceCfg> selectByExample(TraceCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    TraceCfg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") TraceCfg record, @Param("example") TraceCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    int updateByExample(@Param("record") TraceCfg record, @Param("example") TraceCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    int updateByPrimaryKeySelective(TraceCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trace_cfg
     *
     * @mbggenerated Mon Jun 11 08:58:33 CST 2018
     */
    int updateByPrimaryKey(TraceCfg record);
}